// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xzs_func.h"

extern XZs_func_Config XZs_func_ConfigTable[];

XZs_func_Config *XZs_func_LookupConfig(u16 DeviceId) {
	XZs_func_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XZS_FUNC_NUM_INSTANCES; Index++) {
		if (XZs_func_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XZs_func_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XZs_func_Initialize(XZs_func *InstancePtr, u16 DeviceId) {
	XZs_func_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XZs_func_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XZs_func_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

