// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void doGain (
hls::stream<struct ap_axis<32, 2, 5, 6 > >& inStream,
hls::stream<struct ap_axis<32, 2, 5, 6 > >& outStream,
int gain);
