// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "doGain.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic doGain::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic doGain::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> doGain::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> doGain::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> doGain::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> doGain::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> doGain::ap_ST_st5_fsm_4 = "10000";
const sc_lv<7> doGain::ap_ST_st6_fsm_5 = "100000";
const sc_lv<7> doGain::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<32> doGain::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> doGain::ap_const_lv1_1 = "1";
const int doGain::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> doGain::ap_const_lv32_1 = "1";
const sc_lv<1> doGain::ap_const_lv1_0 = "0";
const sc_lv<7> doGain::ap_const_lv7_0 = "0000000";
const sc_lv<32> doGain::ap_const_lv32_6 = "110";
const sc_lv<7> doGain::ap_const_lv7_64 = "1100100";
const sc_lv<7> doGain::ap_const_lv7_1 = "1";

doGain::doGain(sc_module_name name) : sc_module(name), mVcdFile(0) {
    doGain_CRTL_BUS_s_axi_U = new doGain_CRTL_BUS_s_axi<C_S_AXI_CRTL_BUS_ADDR_WIDTH,C_S_AXI_CRTL_BUS_DATA_WIDTH>("doGain_CRTL_BUS_s_axi_U");
    doGain_CRTL_BUS_s_axi_U->AWVALID(s_axi_CRTL_BUS_AWVALID);
    doGain_CRTL_BUS_s_axi_U->AWREADY(s_axi_CRTL_BUS_AWREADY);
    doGain_CRTL_BUS_s_axi_U->AWADDR(s_axi_CRTL_BUS_AWADDR);
    doGain_CRTL_BUS_s_axi_U->WVALID(s_axi_CRTL_BUS_WVALID);
    doGain_CRTL_BUS_s_axi_U->WREADY(s_axi_CRTL_BUS_WREADY);
    doGain_CRTL_BUS_s_axi_U->WDATA(s_axi_CRTL_BUS_WDATA);
    doGain_CRTL_BUS_s_axi_U->WSTRB(s_axi_CRTL_BUS_WSTRB);
    doGain_CRTL_BUS_s_axi_U->ARVALID(s_axi_CRTL_BUS_ARVALID);
    doGain_CRTL_BUS_s_axi_U->ARREADY(s_axi_CRTL_BUS_ARREADY);
    doGain_CRTL_BUS_s_axi_U->ARADDR(s_axi_CRTL_BUS_ARADDR);
    doGain_CRTL_BUS_s_axi_U->RVALID(s_axi_CRTL_BUS_RVALID);
    doGain_CRTL_BUS_s_axi_U->RREADY(s_axi_CRTL_BUS_RREADY);
    doGain_CRTL_BUS_s_axi_U->RDATA(s_axi_CRTL_BUS_RDATA);
    doGain_CRTL_BUS_s_axi_U->RRESP(s_axi_CRTL_BUS_RRESP);
    doGain_CRTL_BUS_s_axi_U->BVALID(s_axi_CRTL_BUS_BVALID);
    doGain_CRTL_BUS_s_axi_U->BREADY(s_axi_CRTL_BUS_BREADY);
    doGain_CRTL_BUS_s_axi_U->BRESP(s_axi_CRTL_BUS_BRESP);
    doGain_CRTL_BUS_s_axi_U->ACLK(ap_clk);
    doGain_CRTL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    doGain_CRTL_BUS_s_axi_U->ACLK_EN(doGain_CRTL_BUS_s_axi_U_ap_dummy_ce);
    doGain_CRTL_BUS_s_axi_U->ap_start(ap_start);
    doGain_CRTL_BUS_s_axi_U->interrupt(interrupt);
    doGain_CRTL_BUS_s_axi_U->ap_ready(ap_ready);
    doGain_CRTL_BUS_s_axi_U->ap_done(ap_done);
    doGain_CRTL_BUS_s_axi_U->ap_idle(ap_idle);
    doGain_CRTL_BUS_s_axi_U->gain(gain);
    doGain_mul_32s_32s_32_6_U1 = new doGain_mul_32s_32s_32_6<1,6,32,32,32>("doGain_mul_32s_32s_32_6_U1");
    doGain_mul_32s_32s_32_6_U1->clk(ap_clk);
    doGain_mul_32s_32s_32_6_U1->reset(ap_rst_n_inv);
    doGain_mul_32s_32s_32_6_U1->din0(inStream_TDATA);
    doGain_mul_32s_32s_32_6_U1->din1(gain_read_reg_170);
    doGain_mul_32s_32s_32_6_U1->ce(grp_fu_164_ce);
    doGain_mul_32s_32s_32_6_U1->dout(grp_fu_164_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_124_p2 );
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_124_p2 );
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( inStream_TVALID );
    sensitive << ( exitcond_fu_124_p2 );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_99);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_25 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_99 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_132 );

    SC_METHOD(thread_ap_sig_ioackin_outStream_TREADY);
    sensitive << ( outStream_TREADY );
    sensitive << ( ap_reg_ioackin_outStream_TREADY );

    SC_METHOD(thread_doGain_CRTL_BUS_s_axi_U_ap_dummy_ce);

    SC_METHOD(thread_exitcond_fu_124_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( i_reg_113 );

    SC_METHOD(thread_grp_fu_164_ce);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_ioackin_outStream_TREADY );

    SC_METHOD(thread_i_1_fu_130_p2);
    sensitive << ( i_reg_113 );

    SC_METHOD(thread_inStream_TREADY);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_124_p2 );
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_outStream_TDATA);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( grp_fu_164_p2 );

    SC_METHOD(thread_outStream_TDEST);
    sensitive << ( tmp_dest_V_reg_213 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TID);
    sensitive << ( tmp_id_V_reg_208 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TKEEP);
    sensitive << ( tmp_keep_V_reg_188 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TLAST);
    sensitive << ( tmp_last_V_reg_203 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TSTRB);
    sensitive << ( tmp_strb_V_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TUSER);
    sensitive << ( tmp_user_V_reg_198 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_outStream_TVALID);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_reg_ioackin_outStream_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_124_p2 );
    sensitive << ( ap_sig_bdd_106 );
    sensitive << ( ap_sig_ioackin_outStream_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000001";
    ap_reg_ioackin_outStream_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "doGain_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, inStream_TDATA, "(port)inStream_TDATA");
    sc_trace(mVcdFile, inStream_TVALID, "(port)inStream_TVALID");
    sc_trace(mVcdFile, inStream_TREADY, "(port)inStream_TREADY");
    sc_trace(mVcdFile, inStream_TKEEP, "(port)inStream_TKEEP");
    sc_trace(mVcdFile, inStream_TSTRB, "(port)inStream_TSTRB");
    sc_trace(mVcdFile, inStream_TUSER, "(port)inStream_TUSER");
    sc_trace(mVcdFile, inStream_TLAST, "(port)inStream_TLAST");
    sc_trace(mVcdFile, inStream_TID, "(port)inStream_TID");
    sc_trace(mVcdFile, inStream_TDEST, "(port)inStream_TDEST");
    sc_trace(mVcdFile, outStream_TDATA, "(port)outStream_TDATA");
    sc_trace(mVcdFile, outStream_TVALID, "(port)outStream_TVALID");
    sc_trace(mVcdFile, outStream_TREADY, "(port)outStream_TREADY");
    sc_trace(mVcdFile, outStream_TKEEP, "(port)outStream_TKEEP");
    sc_trace(mVcdFile, outStream_TSTRB, "(port)outStream_TSTRB");
    sc_trace(mVcdFile, outStream_TUSER, "(port)outStream_TUSER");
    sc_trace(mVcdFile, outStream_TLAST, "(port)outStream_TLAST");
    sc_trace(mVcdFile, outStream_TID, "(port)outStream_TID");
    sc_trace(mVcdFile, outStream_TDEST, "(port)outStream_TDEST");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWVALID, "(port)s_axi_CRTL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWREADY, "(port)s_axi_CRTL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWADDR, "(port)s_axi_CRTL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WVALID, "(port)s_axi_CRTL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WREADY, "(port)s_axi_CRTL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WDATA, "(port)s_axi_CRTL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WSTRB, "(port)s_axi_CRTL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARVALID, "(port)s_axi_CRTL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARREADY, "(port)s_axi_CRTL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARADDR, "(port)s_axi_CRTL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RVALID, "(port)s_axi_CRTL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RREADY, "(port)s_axi_CRTL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RDATA, "(port)s_axi_CRTL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RRESP, "(port)s_axi_CRTL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BVALID, "(port)s_axi_CRTL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BREADY, "(port)s_axi_CRTL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BRESP, "(port)s_axi_CRTL_BUS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_25, "ap_sig_bdd_25");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, gain, "gain");
    sc_trace(mVcdFile, doGain_CRTL_BUS_s_axi_U_ap_dummy_ce, "doGain_CRTL_BUS_s_axi_U_ap_dummy_ce");
    sc_trace(mVcdFile, gain_read_reg_170, "gain_read_reg_170");
    sc_trace(mVcdFile, i_1_fu_130_p2, "i_1_fu_130_p2");
    sc_trace(mVcdFile, i_1_reg_178, "i_1_reg_178");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_99, "ap_sig_bdd_99");
    sc_trace(mVcdFile, exitcond_fu_124_p2, "exitcond_fu_124_p2");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, tmp_keep_V_reg_188, "tmp_keep_V_reg_188");
    sc_trace(mVcdFile, tmp_strb_V_reg_193, "tmp_strb_V_reg_193");
    sc_trace(mVcdFile, tmp_user_V_reg_198, "tmp_user_V_reg_198");
    sc_trace(mVcdFile, tmp_last_V_reg_203, "tmp_last_V_reg_203");
    sc_trace(mVcdFile, tmp_id_V_reg_208, "tmp_id_V_reg_208");
    sc_trace(mVcdFile, tmp_dest_V_reg_213, "tmp_dest_V_reg_213");
    sc_trace(mVcdFile, i_reg_113, "i_reg_113");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, ap_sig_ioackin_outStream_TREADY, "ap_sig_ioackin_outStream_TREADY");
    sc_trace(mVcdFile, grp_fu_164_p2, "grp_fu_164_p2");
    sc_trace(mVcdFile, ap_reg_ioackin_outStream_TREADY, "ap_reg_ioackin_outStream_TREADY");
    sc_trace(mVcdFile, grp_fu_164_ce, "grp_fu_164_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("doGain.hdltvin.dat");
    mHdltvoutHandle.open("doGain.hdltvout.dat");
}

doGain::~doGain() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete doGain_CRTL_BUS_s_axi_U;
    delete doGain_mul_32s_32s_32_6_U1;
}

void doGain::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_outStream_TREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
              !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outStream_TREADY.read())))) {
            ap_reg_ioackin_outStream_TREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, outStream_TREADY.read())))) {
            ap_reg_ioackin_outStream_TREADY = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outStream_TREADY.read()))) {
        i_reg_113 = i_1_reg_178.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_113 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        gain_read_reg_170 = gain.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !ap_sig_bdd_106.read())) {
        i_1_reg_178 = i_1_fu_130_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0) && !ap_sig_bdd_106.read())) {
        tmp_dest_V_reg_213 = inStream_TDEST.read();
        tmp_id_V_reg_208 = inStream_TID.read();
        tmp_keep_V_reg_188 = inStream_TKEEP.read();
        tmp_last_V_reg_203 = inStream_TLAST.read();
        tmp_strb_V_reg_193 = inStream_TSTRB.read();
        tmp_user_V_reg_198 = inStream_TUSER.read();
    }
}

void doGain::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !ap_sig_bdd_106.read() && 
         !esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void doGain::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void doGain::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !ap_sig_bdd_106.read() && 
         !esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void doGain::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void doGain::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = (esl_seteq<1,1,1>(inStream_TVALID.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0));
}

void doGain::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void doGain::thread_ap_sig_bdd_25() {
    ap_sig_bdd_25 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void doGain::thread_ap_sig_bdd_99() {
    ap_sig_bdd_99 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void doGain::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_25.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void doGain::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_99.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void doGain::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_132.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void doGain::thread_ap_sig_ioackin_outStream_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_outStream_TREADY.read())) {
        ap_sig_ioackin_outStream_TREADY = outStream_TREADY.read();
    } else {
        ap_sig_ioackin_outStream_TREADY = ap_const_logic_1;
    }
}

void doGain::thread_doGain_CRTL_BUS_s_axi_U_ap_dummy_ce() {
    doGain_CRTL_BUS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
}

void doGain::thread_exitcond_fu_124_p2() {
    exitcond_fu_124_p2 = (!i_reg_113.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_113.read() == ap_const_lv7_64);
}

void doGain::thread_grp_fu_164_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          ap_sig_bdd_106.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outStream_TREADY.read())))) {
        grp_fu_164_ce = ap_const_logic_0;
    } else {
        grp_fu_164_ce = ap_const_logic_1;
    }
}

void doGain::thread_i_1_fu_130_p2() {
    i_1_fu_130_p2 = (!i_reg_113.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_113.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void doGain::thread_inStream_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0) && 
          !ap_sig_bdd_106.read()))) {
        inStream_TREADY = ap_const_logic_1;
    } else {
        inStream_TREADY = ap_const_logic_0;
    }
}

void doGain::thread_outStream_TDATA() {
    outStream_TDATA = grp_fu_164_p2.read();
}

void doGain::thread_outStream_TDEST() {
    outStream_TDEST = tmp_dest_V_reg_213.read();
}

void doGain::thread_outStream_TID() {
    outStream_TID = tmp_id_V_reg_208.read();
}

void doGain::thread_outStream_TKEEP() {
    outStream_TKEEP = tmp_keep_V_reg_188.read();
}

void doGain::thread_outStream_TLAST() {
    outStream_TLAST = tmp_last_V_reg_203.read();
}

void doGain::thread_outStream_TSTRB() {
    outStream_TSTRB = tmp_strb_V_reg_193.read();
}

void doGain::thread_outStream_TUSER() {
    outStream_TUSER = tmp_user_V_reg_198.read();
}

void doGain::thread_outStream_TVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_outStream_TREADY.read())))) {
        outStream_TVALID = ap_const_logic_1;
    } else {
        outStream_TVALID = ap_const_logic_0;
    }
}

void doGain::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!ap_sig_bdd_106.read() && !esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else if ((esl_seteq<1,1,1>(exitcond_fu_124_p2.read(), ap_const_lv1_0) && !ap_sig_bdd_106.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outStream_TREADY.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

void doGain::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TDATA\" :  \"" << inStream_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TVALID\" :  \"" << inStream_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"inStream_TREADY\" :  \"" << inStream_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TKEEP\" :  \"" << inStream_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TSTRB\" :  \"" << inStream_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TUSER\" :  \"" << inStream_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TLAST\" :  \"" << inStream_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TID\" :  \"" << inStream_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inStream_TDEST\" :  \"" << inStream_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TDATA\" :  \"" << outStream_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TVALID\" :  \"" << outStream_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outStream_TREADY\" :  \"" << outStream_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TKEEP\" :  \"" << outStream_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TSTRB\" :  \"" << outStream_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TUSER\" :  \"" << outStream_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TLAST\" :  \"" << outStream_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TID\" :  \"" << outStream_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outStream_TDEST\" :  \"" << outStream_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWVALID\" :  \"" << s_axi_CRTL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_AWREADY\" :  \"" << s_axi_CRTL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWADDR\" :  \"" << s_axi_CRTL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WVALID\" :  \"" << s_axi_CRTL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_WREADY\" :  \"" << s_axi_CRTL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WDATA\" :  \"" << s_axi_CRTL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WSTRB\" :  \"" << s_axi_CRTL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARVALID\" :  \"" << s_axi_CRTL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_ARREADY\" :  \"" << s_axi_CRTL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARADDR\" :  \"" << s_axi_CRTL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RVALID\" :  \"" << s_axi_CRTL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_RREADY\" :  \"" << s_axi_CRTL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RDATA\" :  \"" << s_axi_CRTL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RRESP\" :  \"" << s_axi_CRTL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BVALID\" :  \"" << s_axi_CRTL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_BREADY\" :  \"" << s_axi_CRTL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BRESP\" :  \"" << s_axi_CRTL_BUS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

