// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XZS_FUNC_H
#define XZS_FUNC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xzs_func_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XZs_func_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XZs_func;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XZs_func_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XZs_func_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XZs_func_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XZs_func_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XZs_func_Initialize(XZs_func *InstancePtr, u16 DeviceId);
XZs_func_Config* XZs_func_LookupConfig(u16 DeviceId);
int XZs_func_CfgInitialize(XZs_func *InstancePtr, XZs_func_Config *ConfigPtr);
#else
int XZs_func_Initialize(XZs_func *InstancePtr, const char* InstanceName);
int XZs_func_Release(XZs_func *InstancePtr);
#endif

void XZs_func_Start(XZs_func *InstancePtr);
u32 XZs_func_IsDone(XZs_func *InstancePtr);
u32 XZs_func_IsIdle(XZs_func *InstancePtr);
u32 XZs_func_IsReady(XZs_func *InstancePtr);
void XZs_func_EnableAutoRestart(XZs_func *InstancePtr);
void XZs_func_DisableAutoRestart(XZs_func *InstancePtr);
u32 XZs_func_Get_return(XZs_func *InstancePtr);


void XZs_func_InterruptGlobalEnable(XZs_func *InstancePtr);
void XZs_func_InterruptGlobalDisable(XZs_func *InstancePtr);
void XZs_func_InterruptEnable(XZs_func *InstancePtr, u32 Mask);
void XZs_func_InterruptDisable(XZs_func *InstancePtr, u32 Mask);
void XZs_func_InterruptClear(XZs_func *InstancePtr, u32 Mask);
u32 XZs_func_InterruptGetEnabled(XZs_func *InstancePtr);
u32 XZs_func_InterruptGetStatus(XZs_func *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
