// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "input_r"
#define AUTOTB_TVIN_input_r  "../tv/cdatafile/c.zhan_suen.autotvin_input_r.dat"
// wrapc file define: "result"
#define AUTOTB_TVOUT_result  "../tv/cdatafile/c.zhan_suen.autotvout_result.dat"
#define AUTOTB_TVIN_result  "../tv/cdatafile/c.zhan_suen.autotvin_result.dat"
// wrapc file define: "y"
#define AUTOTB_TVIN_y  "../tv/cdatafile/c.zhan_suen.autotvin_y.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "result"
#define AUTOTB_TVOUT_PC_result  "../tv/rtldatafile/rtl.zhan_suen.autotvout_result.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			input_r_depth = 0;
			result_depth = 0;
			y_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{input_r " << input_r_depth << "}\n";
			total_list << "{result " << result_depth << "}\n";
			total_list << "{y " << y_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int input_r_depth;
		int result_depth;
		int y_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define zhan_suen AESL_ORIG_DUT_zhan_suen
extern void zhan_suen (
int input[100],
int result[100],
int y);
#undef zhan_suen

void zhan_suen (
int input[100],
int result[100],
int y)
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "result"
		aesl_fh.read(AUTOTB_TVOUT_PC_result, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_result, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_result, AESL_token); // data

			sc_bv<32> *result_pc_buffer = new sc_bv<32>[100];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'result', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'result', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					result_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_result, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_result))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: result
				{
					// bitslice(31, 0)
					// {
						// celement: result(31, 0)
						// {
							sc_lv<32>* result_lv0_0_99_1 = new sc_lv<32>[100];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: result(31, 0)
						{
							// carray: (0) => (99) @ (1)
							for (int i_0 = 0; i_0 <= 99; i_0 += 1)
							{
								if (&(result[0]) != NULL) // check the null address if the c port is array or others
								{
									result_lv0_0_99_1[hls_map_index++].range(31, 0) = sc_bv<32>(result_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: result(31, 0)
						{
							// carray: (0) => (99) @ (1)
							for (int i_0 = 0; i_0 <= 99; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : result[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : result[0]
								// output_left_conversion : result[i_0]
								// output_type_conversion : (result_lv0_0_99_1[hls_map_index++]).to_uint64()
								if (&(result[0]) != NULL) // check the null address if the c port is array or others
								{
									result[i_0] = (result_lv0_0_99_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] result_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "input_r"
		char* tvin_input_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_input_r);

		// "result"
		char* tvin_result = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_result);
		char* tvout_result = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_result);

		// "y"
		char* tvin_y = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_y);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_input_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);

		sc_bv<32>* input_r_tvin_wrapc_buffer = new sc_bv<32>[100];

		// RTL Name: input_r
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: input(31, 0)
				{
					// carray: (0) => (99) @ (1)
					for (int i_0 = 0; i_0 <= 99; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : input[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : input[0]
						// regulate_c_name       : input
						// input_type_conversion : input[i_0]
						if (&(input[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> input_tmp_mem;
							input_tmp_mem = input[i_0];
							input_r_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = input_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 100; i++)
		{
			sprintf(tvin_input_r, "%s\n", (input_r_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);
		}

		tcl_file.set_num(100, &tcl_file.input_r_depth);
		sprintf(tvin_input_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_input_r, tvin_input_r);

		// release memory allocation
		delete [] input_r_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_result, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_result, tvin_result);

		sc_bv<32>* result_tvin_wrapc_buffer = new sc_bv<32>[100];

		// RTL Name: result
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: result(31, 0)
				{
					// carray: (0) => (99) @ (1)
					for (int i_0 = 0; i_0 <= 99; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : result[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : result[0]
						// regulate_c_name       : result
						// input_type_conversion : result[i_0]
						if (&(result[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> result_tmp_mem;
							result_tmp_mem = result[i_0];
							result_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = result_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 100; i++)
		{
			sprintf(tvin_result, "%s\n", (result_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_result, tvin_result);
		}

		tcl_file.set_num(100, &tcl_file.result_depth);
		sprintf(tvin_result, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_result, tvin_result);

		// release memory allocation
		delete [] result_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_y, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_y, tvin_y);

		sc_bv<32> y_tvin_wrapc_buffer;

		// RTL Name: y
		{
			// bitslice(31, 0)
			{
				// celement: y(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : y
						// sub_1st_elem          : 
						// ori_name_1st_elem     : y
						// regulate_c_name       : y
						// input_type_conversion : y
						if (&(y) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> y_tmp_mem;
							y_tmp_mem = y;
							y_tvin_wrapc_buffer.range(31, 0) = y_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_y, "%s\n", (y_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_y, tvin_y);
		}

		tcl_file.set_num(1, &tcl_file.y_depth);
		sprintf(tvin_y, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_y, tvin_y);

// [call_c_dut] ---------->

		AESL_ORIG_DUT_zhan_suen(input, result, y);


		// [[transaction]]
		sprintf(tvout_result, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_result, tvout_result);

		sc_bv<32>* result_tvout_wrapc_buffer = new sc_bv<32>[100];

		// RTL Name: result
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: result(31, 0)
				{
					// carray: (0) => (99) @ (1)
					for (int i_0 = 0; i_0 <= 99; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : result[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : result[0]
						// regulate_c_name       : result
						// input_type_conversion : result[i_0]
						if (&(result[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> result_tmp_mem;
							result_tmp_mem = result[i_0];
							result_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = result_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 100; i++)
		{
			sprintf(tvout_result, "%s\n", (result_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_result, tvout_result);
		}

		tcl_file.set_num(100, &tcl_file.result_depth);
		sprintf(tvout_result, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_result, tvout_result);

		// release memory allocation
		delete [] result_tvout_wrapc_buffer;

		// release memory allocation: "input_r"
		delete [] tvin_input_r;
		// release memory allocation: "result"
		delete [] tvout_result;
		delete [] tvin_result;
		// release memory allocation: "y"
		delete [] tvin_y;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

