# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/saptarshi/Documents/AEP/project_fulladder/project_fulladder.cache/wt [current_project]
set_property parent.project_path /home/saptarshi/Documents/AEP/project_fulladder/project_fulladder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /home/saptarshi/Documents/AEP/project_fulladder/project_fulladder.srcs/sources_1/new/FullAdder.vhd
synth_design -top FullAdder -part xc7z020clg484-1
write_checkpoint -noxdef FullAdder.dcp
catch { report_utilization -file FullAdder_utilization_synth.rpt -pb FullAdder_utilization_synth.pb }
