// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "/home/saptarshi/Documents/AEP/zhangsueng.c"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/saptarshi/Documents/AEP/zhangsueng.c"

#ifndef HLS_FASTSIM
#include "apatb_zhangsueng.h"
#endif
#define zhangsueng(...) AESL_ORIG_DUT_zhangsueng(__VA_ARGS__)
#1 "/home/saptarshi/Documents/AEP/zhangsueng.c"
int zhangsueng(int a ,int b)
{
 int c;
 c=a+b;
 return c;
}
#undef zhangsueng

#6 "/home/saptarshi/Documents/AEP/zhangsueng.c"
